---
abstract: 'Simple SVK interface for Padre'
author:
  - 'Gabor Szabo <szabgab@gmail.com>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Padre-Plugin-SVK
no_index:
  directory:
    - inc
    - t
requires:
  Capture::Tiny: 0.03
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
